abeja-inc/abeja-platform-cli

abejacli/bucket/upload_job.py, tests/unit/bucket/upload_job_test.py, tests/unit/datalake/upload_job_test.py
Bucketでファイルアップロード失敗時のRetryにバグがあったので修正しました。必要なパラメータを渡すように変更しています。
https://github.com/abeja-inc/platform-planning/issues/3204
=> Pass `destination` for retrying bucket upload file

abejacli/session.py, tests/__init__.py, tests/integration/abeja_test.py
Integration testで実際のAPIエンドポイントを叩くが、ログからはそれがテストかユーザーかわからずdeprecatedなエンドポイントの利用実績を調査するのに困ったので、対応。
=> Change `User-Agent` when test

abejacli/run.py, abejacli/session.py, tests/integration/abeja_test.py, tests/unit/model/deployment_test.py
`models` 関係のエンドポイントを廃止しました。
https://github.com/abeja-inc/platform-planning/issues/3199
=> Deprecate `/models` endpoint

abejacli/run.py
describe-channelsのデフォルト100件という表記を、デフォルト1000件に修正
=> fix-command-line-text

abejacli/training/__init__.py, abejacli/training/commands.py, tests/unit/training/commands_test.py, tests/unit/training/training_test.py
Training config schemaを実体に合うように修正しました。
後方互換性はあります。
- `debug-local`, `local-run`, `create-job`, `create-version`, `create-notebook` の実体にあうように対応するschemaのvalidationを更新
- `training.yaml` のcerberus validationで `allow_unknown=True` を設定
- `instance_type` を `training.yaml` で指定できるように修正
- 各種バグフィックス
https://github.com/abeja-inc/platform-planning/issues/2995
=> Update training config schema

abejacli/training/commands.py, tests/unit/training/commands_test.py
`train-local` で `--name` が必須だが、configファイルにある場合はそちらから補えるように変更。
https://github.com/abeja-inc/platform-planning/issues/3299
=> Relax the restriction of specifying `name` on `train-local`

abejacli/training/commands.py, tests/unit/training/commands_test.py
https://github.com/abeja-inc/platform-planning/issues/3475
`--export-log` オプションを付けると
リクエストボディに `{"export_log": true}` が追加され、
19.04 以降のイメージを使っていれば、[.abeja_train.log という名前のログファイルを artifact に含めるようになります](https://github.com/abeja-inc/platform-model-proxy/pull/59)。
=> add option export-log on training create-training-job command

.circleci/config.yml, Makefile, abejacli/training/commands.py
ちょっと迷ったけど、 training サブコマンド内では統一して
description のショートハンドオプションを `-d`
としました。
あと、全体的にざっと眺めたけど、他にはショートハンドオプションが重複しているものはなさそうでした。
（[download_job_result](https://github.com/abeja-inc/abeja-platform-cli/blob/develop/abejacli/training/commands.py#L670-L674) の `-jd` は斬新だな、と思ったけど）
=> fix a duplicate short hand options

abejacli/training/commands.py
ドキュメント書いてたら、 `create-job` コマンドで `--datasets` から `-d` オプション削っただけで、 `--description` に追加してないことに気づいたので追加。
軽微な修正なので、 CI が通ったらセルフマージします。
=> add shorthand option for description on create-job command

.circleci/config.yml, README.md, abejacli/docker/container_run.py, abejacli/model/docker_handler.py, poetry.lock, pyproject.toml
[ABEJA Platform SDK および CLI のサポートする Python バージョンが 3.6 以降になります - Announcement - ABEJA, Inc.](https://forums.abeja.io/t/topic/230) に伴う移行差分です。
- `poetry update` したことで依存ライブラリのバージョンが上がっていますが、six など不要になるライブラリもあるため、このままにしておきます。
**2020/10/01 以降にマージするため、Draft のままにしておきます。**
=> Switch python version to 3.6

.github/workflows/cli.yaml
https://github.com/abeja-inc/abeja-platform-cli/pull/36#discussion_r859395854
ビルドマトリックスを使って複数の Python バージョンで CI するようにしました。
=> use matrix setting for ci each python version

.github/workflows/cli.yaml, poetry.lock, pyproject.toml
https://github.com/abeja-inc/platform-planning/issues/3966
ruamel.yaml のバージョンが古いと Python3.10 でインストールできないようなので、バージョンアップして様子を見る。
別 PR で dependabot のアラートも対応したら、2.1.0 くらいのバージョンで PyPI へのリリースを試みようと思います。
=> update ruamel.yaml version

.github/workflows/cli.yaml
https://github.com/abeja-inc/abeja-platform-cli/actions/runs/2255787366
リリースビルドの Integration Test で 403 エラー。
ABEJA_API_URL が dev 環境用のままだったので prod 環境用に修正。。。
Github Actions の設定修正のみなので、CI 通ったらセルフマージします。。
=> fix api url for integration test

abejacli/dx_template/commands.py, abejacli/run.py
- `abeja dx-templates init` コマンドを実装しました。
- click ライブラリを利用した`abeja dx-templates init` コマンドの新規作成
- template.yaml の自動生成
- `https://github.com/abeja-inc/platform-dx-template-samples.git` からの`git clone` 実行
- ユーザ入力のサニタイズ処理追加
- エラーハンドリング実装
- help コマンドの表示
- `abeja dx-templates init` コマンド の正常実行
- 実行引数あり
- インタラクティブ入力
- 準正常系のエラー確認
- サニタイズ処理
- organization_id は他のコマンド同様にconfig から取ってきます。
- template.yaml は今後変更もありそうだが、まずは第一弾として必要最低限の構成にしています。
=> 【initコマンド】abeja dx-templates init コマンド実装

abejacli/dx_template/commands.py
- dx-template push コマンドを実装しました
- click ライブラリをつかってpush コマンドを実装
- 必須ファイルの存在確認するバリデーション処理の実装
- handler.py は同階層以下のディレクトリとファイルも全て含めてzip 圧縮する処理の実装
- 既存コードにすでに実装済みのrequests ライブラリのラッパー関数を利用して、arms のDX template API へのPOST リクエストを行う処理を実装
- 認証は`abeja-cli config init` で設定した内容を使い回す
- 正常系リクエスト/レスポンスの実行確認
- バリデーション及び通信エラーの準正常系の実行確認
=> 【pushコマンド】abeja-platform-cli に abeja dx-templates push コマンドを追加

abejacli/dx_template/commands.py
- template.yaml のフォーマット変更に伴うinit コマンドのロジック変更を行いました。
- フォーマット変更とともに、template.yaml はskeleton のリポジトリに保存される形になったので、その変更への追従も同時に実施
- `https://github.com/abeja-inc/platform-dx-template-samples.git` からのファイルダウンロード要否の選択を無くして必ずダウンロードされるように変更
- template.yaml を上記skeleton リポジトリに格納されているものをベースにユーザ入力値を反映させて作成されるように変更
- skeleton リポジトリのURL 変更
- init コマンド実行してskeleton ダウンロードの有無を聞かれることなくファイルが手元に配置されることを確認
- template.yaml が複数あることでDX テンプレート開発者に混乱を招く恐れがあるため、以下の対処は削除しました。
- ~処理の中でtemplate.yaml はユーザ入力値で上書きしますが、yaml ライブラリの仕様上、コメントが消えてしまうので、更新前のtemplate.yaml を`templateUsage.yaml` というファイル名で別名保存するようにしています。（開発者向けのコメントがマニュアルがわりに使えそうだから）~
=> 【DX テンプレート一覧】abeja-platform-cli の init コマンド修正

.gitignore, abejacli/dx_template/commands.py, poetry.lock, pyproject.toml
ABEJA Platform CLI の `dx-template push` コマンド実行後に、DXテンプレート用サムネイル画像の解像度チェック（800x600以下）とファイルサイズチェック（512KB以下）を追加しました。
｛abeja-platform-cli = local 環境・ARMS = dev 環境｝にて、`dx-template push` コマンド実行時の以下の動作を確認しました
```sh
sakai@sakai-dev:~/abeja-platform/abeja-platform-cli/.debug$ sh run_cli_local.sh 
Upload succeeded
{
"updated_at": "2023-07-10T07:04:42Z",
"thumbnail_base64": null,
"template_yaml_base64": null,
"scope": "private",
"organization_id": "2818232766522",
"name": "sakai-test",
"inserted_at": "2023-07-10T07:04:42Z",
"id": "3106817360936",
"description": "",
"abeja_user_only": true
}
✨✨✨✨ It's done!! Happy DX! ✨✨✨✨
```
```sh
sakai@sakai-dev:~/abeja-platform/abeja-platform-cli$ poetry run python -m abejacli.run dx-template push --directory_path sakai-test
Resolution of …
```
=> 【DX テンプレート一覧】dx-template push コマンド実行時にDXテンプレート用サムネイル画像のサイズチェックを追加する

abejacli/dx_template/commands.py
`dxtemplate init` 実行後に自動的に作成される `template.yaml` が、元の platform-dx-template-skeleton-v1 レポジトリの `template.yaml` の内容からのキーの順番が変化したり、コメントが消えてしまう問題があったので、それを修正しました
=> Keep yaml format in dxtemplate init command

abejacli/dx_template/commands.py, poetry.lock, pyproject.toml
`dxtemplate push` コマンドでDXテンプレート登録する際に、`template.yaml` のファイルフォーマット validation 処理を追加しました。
validation 処理は Yamale を用いて、platform-dx-template-skeleton-v1 レポジトリの `[template_schema.yaml](https://github.com/abeja-inc/platform-dx-template-skeleton-v1/blob/main/template_schema.yaml)` をもとに行われます
=> Valid template.yaml in dxtemplate push command

abejacli/labs/commands.py, tests/unit/labs/commands_test.py
`abeja labs init` コマンド実行時に、Labs アプリ設定ファイル `setting.yaml` の GitHub レポジトリ URL を Labs アプリ名で上書きするようにしました
=> [ABEJA Platform Labs] Add github URL in labs init command

abejacli/labs/commands.py
`abeja labs init` コマンドにて、'react' の app_type を設定できるようにしました
=> [ABEJA Platform Labs] Add react in app_type args of labs-init command

abejacli/labs/commands.py, tests/unit/labs/commands_test.py
APF Labs の上書き登録用の各種コマンドを追加しました
- Labs アプリ作成コマンド（`abeja labs push`）にて、同名 Labs アプリを上書き登録できるようにしました
- Labs アプリ上書き登録コマンド（`abeja labs update`）を追加しました
- Labs アプリ削除コマンド（`abeja labs delete`）を追加しました
=> [Labs] Add labs commands to overwrite app
